[package]
name = "trace"
version = "0.1.0"
edition = "2024"

[features]
no-color = []

[dependencies]
trace-macro = { path = "./trace-macro" }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
